### ISSUE TITLE
maven build fails when the path to source contains a blank

### ISSUE THREAD

**Issue by mawinter69** [jenkinsci/maven-hpi-plugin#441]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
version 3.38 of maven-hpi-plugin

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows

### Reproduction steps

1. put the sources of your plugin in a folder that contains a blank, e.g. c:\data\dev\jenkins\my plugins\myplugin
2. run mvn clean install

### Expected Results

The build succeeds

### Actual Results

the build fails with 
`Error: Could not find or load main class plugins\pipeline-groovy-lib-plugin\target\patch-modules\org-netbeans-insane-hook.jar`

`[ERROR] Command was cmd.exe /X /C ""...  --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.desktop/com.sun.beans.introspect=ALL-UNNAMED --patch-module=java.base=C:\data\dev\jenkins\my plugins\pipeline-groovy-lib-plugin\target\patch-modules\org-netbeans-insane-hook.jar --add-exports=java.base/org.netbeans.insane.hook=ALL-UNNAMED ..." #`

**Comment by jtnord** [comment]
https://github.com/jenkinsci/maven-hpi-plugin/blob/fe7527cbb6fb9eefbbae434803a5c6fbdadb34be/src/main/java/org/jenkinsci/maven/plugins/hpi/TestRuntimeMojo.java#L134

**Comment by basil** [comment]
Fixed in #445. Released in [3.39](https://github.com/jenkinsci/maven-hpi-plugin/releases/tag/maven-hpi-plugin-3.39).
