### ISSUE TITLE
WebSocket CLI not working from `hpi:run`

### ISSUE THREAD

**Issue by jglick** [jenkinsci/maven-hpi-plugin#523]
In both 2.361.x and 2.401.x, a controller started with `hpi:run` does not serve WebSocket CLI requests:

```
java.lang.NullPointerException
	at jenkins.websocket.Jetty10Provider.handle(Jetty10Provider.java:67)
	at jenkins.websocket.WebSockets.lambda$upgrade$0(WebSockets.java:70)
```

or

```
java.lang.NullPointerException
	at jenkins.websocket.Jetty10Provider.init(Jetty10Provider.java:68)
	at jenkins.websocket.Jetty10Provider.handle(Jetty10Provider.java:75)
	at jenkins.websocket.WebSockets.lambda$upgrade$0(WebSockets.java:70)
```

Looks like

```java
JettyWebSocketServerContainer.getContainer(req.getServletContext())
```

is null. I am guessing this broke in #409 but have not checked yet. `websocket-core-server-10.0.15.jar` are in the classpath of the plugin but perhaps something else needs to be done to activate WebSocket. Have also not yet checked whether WebSocket agents work, but I suppose not, given that the error is in `WebSockets` before the specific handler code is even run.

**Comment by basil** [comment]
> I am guessing this broke in https://github.com/jenkinsci/maven-hpi-plugin/pull/409 but have not checked yet.

This is an allegation of a regression without proof. If there is proof of a regression, I will investigate this ticket.

If there is merely an allegation without proof, I will not investigate.
