### ISSUE TITLE
Using Java17 for (private) plugin - config ignored after #578

### ISSUE THREAD

**Issue by PiersRBME** [jenkinsci/maven-hpi-plugin#656]
I maintain a private plugin which happens to use some Java17 features. Up to pull #578 the configuration selecting Java 17 in my pom.xml was respected. After that change the properties in my pom.xml are seemingly ignored as the code in that change (setCompilerProperties()) seems to always override the Java version, to 11 .

I have tried to use -Pjava-level-17 (from https://github.com/jenkinsci/plugin-pom/pull/893) but that doesn't seem to have any effect, either.

Is there some configuration I can set in my pom.xml, or some other env/command-line setting to restore the previous function? Or is it frowned upon / not expect that plugins might be built other than on Java 11?

I'm not entirely sure if this is a maven-hpi-plugin thing or a plugin parent pom thing. I'm pretty competent, but not an expert in the Java/Maven space.

**Comment by basil** [comment]
Can you depend on Jenkins 2.463 or newer? That is the first core release to require Java 17 bytecode.

**Comment by PiersRBME** [comment]
Hi - yes, we track Weekly on the instance where the private plugin is installed so that's possible.

Selecting this <jenkins.version> I see how it influences the minimum JDK selected by the setCompilerProperties() from the hpi-plugin. 

So I have a working solution to my particular issue, many thanks for the suggestion. 

Looking at some to-and-fro on previous tickets about this functionality I gather it's intended to be a workaround for the Java 17 transition and may go away again, but it was suprising how it overrode explicit properties in my own pom.
